In [307]:
import pandas as pd

In [308]:
df = pd.read_csv('user-item.csv')
df

,User,Title,Rating,link_suffixes
0,hoshiakari,0cm4,4.0,/26095-0cm4
1,hoshiakari,"1 in 10,000 (Act I)",7.0,/30815-1-in-10-000-act-i
2,hoshiakari,1 Litre no Namida,10.0,/2-1-litre-no-namida
3,hoshiakari,1 Litre no Namida Special,7.0,/3114-1-litre-no-namida-special
4,hoshiakari,10 Promises to My Dog,6.0,/509-10-promises-to-my-dog
...,...,...,...,...
78380,Oamen,Us and Them,7.0,/28319-us-and-them
78381,Oamen,Vincenzo,7.0,/61371-vincenzo
78382,Oamen,Weak Hero Class 1,6.0,/702267-weak-hero
78383,Oamen,Memories of Murder,8.5,/990-memories-of-murder
78384,Oamen,The Glory Part 2,6.0,/745581-the-glory-season-2

In [309]:
df.loc[:, 'title_folded'] = df['Title'].astype(str).str.lower()

df

,User,Title,Rating,link_suffixes,title_folded
0,hoshiakari,0cm4,4.0,/26095-0cm4,0cm4
1,hoshiakari,"1 in 10,000 (Act I)",7.0,/30815-1-in-10-000-act-i,"1 in 10,000 (act i)"
2,hoshiakari,1 Litre no Namida,10.0,/2-1-litre-no-namida,1 litre no namida
3,hoshiakari,1 Litre no Namida Special,7.0,/3114-1-litre-no-namida-special,1 litre no namida special
4,hoshiakari,10 Promises to My Dog,6.0,/509-10-promises-to-my-dog,10 promises to my dog
...,...,...,...,...,...
78380,Oamen,Us and Them,7.0,/28319-us-and-them,us and them
78381,Oamen,Vincenzo,7.0,/61371-vincenzo,vincenzo
78382,Oamen,Weak Hero Class 1,6.0,/702267-weak-hero,weak hero class 1
78383,Oamen,Memories of Murder,8.5,/990-memories-of-murder,memories of murder
78384,Oamen,The Glory Part 2,6.0,/745581-the-glory-season-2,the glory part 2

In [310]:
sorted_df = df.sort_values(by=['title_folded'])
sorted_df['frequency'] = sorted_df.groupby('title_folded')['title_folded'].transform('count')
sorted_df

,User,Title,Rating,link_suffixes,title_folded,frequency
27208,9306491,"""Hello, Stepmother""",6.5,/728343-hello-stepmother,"""hello, stepmother""",1
18303,zhengyi95,#Alive,5.5,/38787-alone,#alive,30
43627,haitakaz,#Alive,6.0,/38787-alone,#alive,30
21675,begonia95,#Alive,7.0,/38787-alone,#alive,30
45267,penel,#Alive,7.5,/38787-alone,#alive,30
...,...,...,...,...,...,...
71590,7698003,‏2020 Idol Star Athletics Championships,7.5,/53045-2020-idol-star-athletics-championships,‏2020 idol star athletics championships,3
66716,mianvnndt,‏2020 Idol Star Athletics Championships,7.5,/53045-2020-idol-star-athletics-championships,‏2020 idol star athletics championships,3
21678,begonia95,≥75℃,8.0,/53419-75,≥75℃,3
76086,caspleo_svt,≥75℃,7.0,/53419-75,≥75℃,3
27210,9306491,≥75℃,6.0,/53419-75,≥75℃,3

In [311]:
trimmed_df = sorted_df[sorted_df['frequency'] >= 15]
trimmed_df

,User,Title,Rating,link_suffixes,title_folded,frequency
18303,zhengyi95,#Alive,5.5,/38787-alone,#alive,30
43627,haitakaz,#Alive,6.0,/38787-alone,#alive,30
21675,begonia95,#Alive,7.0,/38787-alone,#alive,30
45267,penel,#Alive,7.5,/38787-alone,#alive,30
76764,Gwilthyunman,#Alive,7.0,/38787-alone,#alive,30
...,...,...,...,...,...,...
43624,gummyyummy58,Zombie Detective,8.0,/61063-zombie-detective,zombie detective,16
69112,9245641,Zombie Detective,3.0,/61063-zombie-detective,zombie detective,16
16689,8742195,Zombie Detective,8.0,/61063-zombie-detective,zombie detective,16
44918,haitakaz,Zombie Detective,6.5,/61063-zombie-detective,zombie detective,16
70721,samenai,Zombie Detective,8.5,/61063-zombie-detective,zombie detective,16

In [312]:
trimmed_df.loc[:,'median_rating'] = trimmed_df.groupby('title_folded')['Rating'].transform('median')

print(trimmed_df)

               User             Title  Rating            link_suffixes  \
18303     zhengyi95            #Alive     5.5             /38787-alone
43627      haitakaz            #Alive     6.0             /38787-alone
21675     begonia95            #Alive     7.0             /38787-alone
45267         penel            #Alive     7.5             /38787-alone
76764  Gwilthyunman            #Alive     7.0             /38787-alone
...             ...               ...     ...                      ...
43624  gummyyummy58  Zombie Detective     8.0  /61063-zombie-detective
69112       9245641  Zombie Detective     3.0  /61063-zombie-detective
16689       8742195  Zombie Detective     8.0  /61063-zombie-detective
44918      haitakaz  Zombie Detective     6.5  /61063-zombie-detective
70721       samenai  Zombie Detective     8.5  /61063-zombie-detective

           title_folded  frequency  median_rating
18303            #alive         30            7.0
43627            #alive         30            7.0
21675            #alive         30            7.0
45267            #alive         30            7.0
76764            #alive         30            7.0
...                 ...        ...            ...
43624  zombie detective         16            8.0
69112  zombie detective         16            8.0
16689  zombie detective         16            8.0
44918  zombie detective         16            8.0
70721  zombie detective         16            8.0

[19458 rows x 7 columns]

/var/folders/10/6h6zw_3x7p70dkxr50fcp0fw0000gn/T/ipykernel_5819/120840722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_df.loc[:,'median_rating'] = trimmed_df.groupby('title_folded')['Rating'].transform('median')

In [313]:
# median_df = trimmed_df.drop_duplicates(subset=['title_folded'])
median_df = trimmed_df[trimmed_df.median_rating >= 7.0]
median_df = median_df.reset_index(drop=True)
# median_df = median_df.drop(columns=['Rating','index'])
median_df

,User,Title,Rating,link_suffixes,title_folded,frequency,median_rating
0,zhengyi95,#Alive,5.5,/38787-alone,#alive,30,7.0
1,haitakaz,#Alive,6.0,/38787-alone,#alive,30,7.0
2,begonia95,#Alive,7.0,/38787-alone,#alive,30,7.0
3,penel,#Alive,7.5,/38787-alone,#alive,30,7.0
4,Gwilthyunman,#Alive,7.0,/38787-alone,#alive,30,7.0
...,...,...,...,...,...,...,...
18835,gummyyummy58,Zombie Detective,8.0,/61063-zombie-detective,zombie detective,16,8.0
18836,9245641,Zombie Detective,3.0,/61063-zombie-detective,zombie detective,16,8.0
18837,8742195,Zombie Detective,8.0,/61063-zombie-detective,zombie detective,16,8.0
18838,haitakaz,Zombie Detective,6.5,/61063-zombie-detective,zombie detective,16,8.0
18839,samenai,Zombie Detective,8.5,/61063-zombie-detective,zombie detective,16,8.0

In [314]:
data = median_df.pivot_table(index='User',columns='title_folded',values='Rating',aggfunc='mean')
data

title_folded,#alive,1 litre no namida,100 days my prince,100-manen no onna-tachi,18 again,2 moons,2 moons 2,200 pounds beauty,20th century girl,2gether,...,you make me dance,you're all surrounded,you're beautiful,you're my pet,your lie in april,your name engraved herein,yu yu hakusho,yyy,zettai bl ni naru sekai vs zettai bl ni naritakunai otoko,zombie detective
User,,,,,,,,,,,,,,,,,,,,,
10810983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7678823,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7692329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7698003,NaN,NaN,7.5,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7961539,NaN,NaN,NaN,NaN,NaN,8.0,5.0,NaN,NaN,6.0,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wildfllower,NaN,NaN,NaN,NaN,0.0,7.0,6.5,NaN,NaN,NaN,...,6.5,NaN,NaN,NaN,NaN,8.0,NaN,NaN,9.5,NaN
xAyuu,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xxmai,NaN,NaN,NaN,NaN,NaN,8.5,6.5,9.0,NaN,7.0,...,6.5,NaN,9.5,4.5,7.5,NaN,NaN,6.5,8.0,NaN
yangela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zhengyi95,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [315]:
data = data.drop(columns = ['history: stay away from me','present perfect','step for you','tsuge & minato'])
data

title_folded,#alive,1 litre no namida,100 days my prince,100-manen no onna-tachi,18 again,2 moons,2 moons 2,200 pounds beauty,20th century girl,2gether,...,you make me dance,you're all surrounded,you're beautiful,you're my pet,your lie in april,your name engraved herein,yu yu hakusho,yyy,zettai bl ni naru sekai vs zettai bl ni naritakunai otoko,zombie detective
User,,,,,,,,,,,,,,,,,,,,,
10810983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7678823,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7692329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7698003,NaN,NaN,7.5,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7961539,NaN,NaN,NaN,NaN,NaN,8.0,5.0,NaN,NaN,6.0,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wildfllower,NaN,NaN,NaN,NaN,0.0,7.0,6.5,NaN,NaN,NaN,...,6.5,NaN,NaN,NaN,NaN,8.0,NaN,NaN,9.5,NaN
xAyuu,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xxmai,NaN,NaN,NaN,NaN,NaN,8.5,6.5,9.0,NaN,7.0,...,6.5,NaN,9.5,4.5,7.5,NaN,NaN,6.5,8.0,NaN
yangela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zhengyi95,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN

In [316]:
data.to_csv('pivoted.csv')

In [329]:
data = pd.read_csv('pivoted.csv',index_col=0)
data

,#alive,1 litre no namida,100 days my prince,100-manen no onna-tachi,18 again,2 moons,2 moons 2,200 pounds beauty,20th century girl,2gether,...,you make me dance,you're all surrounded,you're beautiful,you're my pet,your lie in april,your name engraved herein,yu yu hakusho,yyy,zettai bl ni naru sekai vs zettai bl ni naritakunai otoko,zombie detective
User,,,,,,,,,,,,,,,,,,,,,
10810983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7678823,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7692329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7698003,NaN,NaN,7.5,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7961539,NaN,NaN,NaN,NaN,NaN,8.0,5.0,NaN,NaN,6.0,...,NaN,NaN,6.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wildfllower,NaN,NaN,NaN,NaN,0.0,7.0,6.5,NaN,NaN,NaN,...,6.5,NaN,NaN,NaN,NaN,8.0,NaN,NaN,9.5,NaN
xAyuu,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xxmai,NaN,NaN,NaN,NaN,NaN,8.5,6.5,9.0,NaN,7.0,...,6.5,NaN,9.5,4.5,7.5,NaN,NaN,6.5,8.0,NaN
yangela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zhengyi95,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN